source "http://rubygems.org"

gem "sinatra"
gem "sinatra-authentication", :path => "/Users/jergason/Dropbox/sinatra-authentication"#:git => "git://github.com/jergason/sinatra-authentication.git"
gem "heroku"
gem "rspec"
gem "rack-test"
gem "rake"
gem "haml"
gem "padrino-helpers"
gem "pony"
gem "dm-core"
gem "dm-migrations"
gem "dm-aggregates"
gem "dm-postgres-adapter"
gem "dm-sqlite-adapter"
gem "dm-serializer"
gem "rack-flash"
gem "rack-test"
