source "http://rubygems.org"

gem "sinatra"
gem "sinatra-authentication", :path => "/Users/jergason/Dropbox/sinatra-authentication" #:git => "git://github.com/jergason/sinatra-authentication.git"
gem "rspec"
gem "rack-test"
gem "rake"
gem "haml"
gem "pony"
gem "dm-core"
gem "dm-migrations"
gem "dm-aggregates"
gem "dm-postgres-adapter"
gem "dm-sqlite-adapter"
gem "rack-flash"
gem "awesome_print"
gem "rack-test"
gem "ruby-debug19"
